### ISSUE TITLE
部分软件生成的linglong.yaml 格式有误

### ISSUE THREAD

**Issue by student-ice** [linuxdeepin/linglong-pica#33]
```
系统：uos 1070
linglong-pica： 1.1.2-1
示例软件：org.hsqldb
```
转置软件时生成的linglong.yaml 内容格式错误

下图中提示linglong.yaml 75行有错误
![image](https://github.com/linuxdeepin/linglong-pica/assets/59855569/b5dc5e32-2698-497e-9af3-c6a56eaea28c)

打开linglong.yaml查看75行内容
![image](https://github.com/linuxdeepin/linglong-pica/assets/59855569/24891910-64dc-45c9-b139-3c2ea8f307ce)

发现本应是一行的内容，给分成了两行，导致ll-builder build 报错

手动修正可以成功build

**Comment by student-ice** [comment]
@chenchongbiao

**Comment by chenchongbiao** [comment]
应该是这行字符串有换行符
